import streamlit as st
import os
from groq import Groq
from PyPDF2 import PdfReader
import edge_tts
import asyncio
from streamlit_mic_recorder import mic_recorder 
import io
import time
from fpdf import FPDF

# --- 1. SETUP HALAMAN & CSS ---
st.set_page_config(page_title="Tech & AI Interviewer", page_icon="💻", layout="wide")

st.markdown("""
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
    .stButton>button {
        width: 100%;
        border-radius: 8px;
        font-weight: 600;
    }
    /* Kotak Hint biar lebih terlihat */
    .stInfo {
        border-left: 5px solid #00FF00 !important;
        background-color: #262730 !important;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 🔑 SETTINGS
# ==========================================
# Mengambil API Key dari Streamlit Secrets
try:
    GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
except KeyError:
    GROQ_API_KEY = "" # Antisipasi kalau lupa naruh secret

MODEL_ID = "llama-3.1-8b-instant" 
WHISPER_ID = "whisper-large-v3"
# ==========================================

# --- 2. FUNGSI PENDUKUNG ---

def get_clean_history():
    clean_msgs = []
    for m in st.session_state.messages:
        clean_msgs.append({"role": m["role"], "content": m["content"]})
    return clean_msgs

def speech_to_text(audio_bytes, client):
    try:
        audio_file = ("audio.webm", audio_bytes)
        transcription = client.audio.transcriptions.create(
            file=audio_file, model=WHISPER_ID, language="id", temperature=0.0
        )
        return transcription.text
    except:
        return None

async def text_to_speech(text):
    output_file = "ai_response.mp3"
    try:
        communicate = edge_tts.Communicate(text, "id-ID-GadisNeural")
        await communicate.save(output_file)
        return output_file
    except:
        return None

def get_pdf_text(uploaded_file):
    text = ""
    try:
        reader = PdfReader(uploaded_file)
        for page in reader.pages:
            text += page.extract_text()
    except:
        pass
    return text

def create_pdf(report_text):
    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 15)
            self.cell(0, 10, 'LAPORAN HASIL TECHNICAL INTERVIEW', 0, 1, 'C')
            self.set_font('Arial', 'I', 10)
            self.cell(0, 10, 'Generated by AI Tech Interviewer System', 0, 1, 'C')
            self.line(10, 30, 200, 30)
            self.ln(10)

    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    # Fix karakter encoding biar PDF gak error
    safe_text = report_text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 10, safe_text)
    return pdf.output(dest='S').encode('latin-1')

# --- 3. SIDEBAR ---
with st.sidebar:
    st.title("⚙️ Dashboard")
    
    if not GROQ_API_KEY:
        st.error("⚠️ API Key Kosong. Cek menu Secrets di Streamlit!")
        st.stop()
    else:
        st.success("🟢 System Online")

    with st.expander("📄 Data Kandidat IT/AI", expanded=True):
        uploaded_cv = st.file_uploader("Upload CV (PDF)", type=["pdf"])
        # Wording diubah spesifik IT/AI
        job_desc = st.text_input("Posisi IT/AI yang Dilamar (Wajib)", placeholder="Contoh: AI Engineer, Backend Dev...")

    st.divider()
    st.markdown("### 🎯 Technical Focus")
    # Pilihan mode dirombak total menjadi spesifik IT/AI
    focus_mode = st.selectbox(
        "Pilih Fokus Evaluasi:",
        [
            "Technical Assessment (Coding & Architecture)", 
            "AI/ML Concepts & Algorithms", 
            "IT Problem Solving (Case Study)", 
            "Behavioral (Agile/Tech Team Fit)"
        ]
    )
    
    st.divider()
    if st.button("🔄 Reset Session"):
        st.session_state.clear()
        st.rerun()

# --- 4. LOGIC UTAMA ---
st.markdown("## 💻 Professional AI Tech Interviewer")

client = Groq(api_key=GROQ_API_KEY)

if "messages" not in st.session_state: st.session_state.messages = []
if "last_processed" not in st.session_state: st.session_state.last_processed = None
if "interview_active" not in st.session_state: st.session_state.interview_active = False
if "hint_content" not in st.session_state: st.session_state.hint_content = None

# ==========================================
# 🚀 FLOW 1: HALAMAN MULAI
# ==========================================
if not st.session_state.interview_active:
    st.info(f"💡 Mode Evaluasi: **{focus_mode}**. Pastikan Anda telah memasukkan Posisi Lamaran dan mengunggah CV.")
    
    col_start, col_dummy = st.columns([1, 2])
    with col_start:
        if st.button("🚀 MULAI TECHNICAL INTERVIEW", type="primary"):
            # Pengecekan Wajib Isi Role (Flow General Dihilangkan)
            if not job_desc or job_desc.strip() == "":
                st.error("⚠️ PENTING: Anda WAJIB mengisi 'Posisi IT/AI yang Dilamar' di sidebar sebelum memulai wawancara.")
            else:
                st.session_state.interview_active = True
                
                cv_text = get_pdf_text(uploaded_cv) if uploaded_cv else ""
                
                role_context = f"Posisi IT/AI yang dilamar kandidat: {job_desc}"
                opening_instruction = "Sapa kandidat, konfirmasi posisi IT/AI yang dilamar, dan langsung berikan satu pertanyaan teknis pemanasan terkait posisi tersebut."

                # Logic Focus Mode IT/AI
                focus_instruction = ""
                if focus_mode == "Technical Assessment (Coding & Architecture)":
                    focus_instruction = "Fokus pada pengujian pemahaman arsitektur sistem, efisiensi kode, framework, atau design pattern."
                elif focus_mode == "AI/ML Concepts & Algorithms":
                    focus_instruction = "Fokus pada pemahaman machine learning, deep learning, tuning model, evaluasi metrik, atau pemrosesan dataset."
                elif focus_mode == "IT Problem Solving (Case Study)":
                    focus_instruction = "Berikan studi kasus teknis (misal: server down, database lambat, atau bug di production) dan minta solusi langkah demi langkah."
                elif focus_mode == "Behavioral (Agile/Tech Team Fit)":
                    focus_instruction = "Fokus pada cara kandidat berkolaborasi dalam tim developer (Agile/Scrum), manajemen konflik pull-request, atau saat menghadapi deadline rilis."

                # System Prompt Diubah ke Engineering Manager
                system_instruction = f"""
                Anda adalah Sarah, Engineering Manager dan Technical Recruiter di perusahaan teknologi (Berbahasa Indonesia).
                Anda sedang mewawancarai kandidat secara teknikal.
                {role_context}
                Data CV Kandidat: {cv_text[:2000]}.
                Fokus Evaluasi: {focus_mode}.
                
                PANDUAN WAWANCARA TEKNIS:
                1. {opening_instruction}
                2. Hindari pertanyaan HR umum (seperti kelemahan terbesar). Fokus 100% pada logika teknis, problem solving, dan *hard skills* IT/AI.
                3. {focus_instruction}
                4. Bicara layaknya profesional IT. Gunakan istilah teknis yang tepat sesuai posisi.
                5. Respon ringkas, tajam, dan langsung ke poin (maksimal 3-4 kalimat).
                6. Berikan pertanyaan SATU per SATU. Tunggu jawaban kandidat.
                """
                
                st.session_state.messages.append({"role": "system", "content": system_instruction})

                # Trigger Start
                try:
                    with st.spinner("Engineering Manager sedang bersiap..."):
                        trigger_msg = "Sapa saya untuk memulai technical interview ini."
                        completion = client.chat.completions.create(
                            model=MODEL_ID,
                            messages=get_clean_history() + [{"role": "user", "content": trigger_msg}],
                            temperature=0.7, max_tokens=250
                        )
                        ai_msg = completion.choices[0].message.content
                        audio_file = asyncio.run(text_to_speech(ai_msg))
                        
                        st.session_state.messages.append({
                            "role": "assistant", "content": ai_msg, 
                            "audio_path": audio_file, "autoplay": True 
                        })
                        st.rerun()
                except Exception as e:
                    st.error(f"Gagal Start: {e}")

# ==========================================
# 💬 FLOW 2: SESI CHAT
# ==========================================
else:
    chat_container = st.container()
    with chat_container:
        for i, msg in enumerate(st.session_state.messages):
            if msg['role'] != 'system':
                with st.chat_message(msg["role"], avatar="👩‍💻" if msg["role"] == "assistant" else "👤"):
                    st.markdown(msg["content"])
                    if "audio_path" in msg:
                        is_last = (i == len(st.session_state.messages) - 1)
                        should_play = msg.get("autoplay", False) and is_last
                        st.audio(msg["audio_path"], format="audio/mp3", autoplay=should_play)
    
    # --- TAMPILAN HINT (JIKA ADA) ---
    if st.session_state.hint_content:
        st.info(f"💡 **Ide Jawaban Teknis:**\n\n{st.session_state.hint_content}")

    st.write("---")
    
    # Input Area
    col_mic, col_hint, col_text = st.columns([1, 1, 3])
    
    current_input = None
    input_type = None

    with col_mic:
        st.write("🎤 **Jawab via Suara:**")
        audio_input = mic_recorder(start_prompt="🔴 Rekam", stop_prompt="⏹️ Kirim", key='recorder')
        if audio_input: 
            current_input = audio_input['bytes']
            input_type = "audio"

    # --- FITUR HINT FIX (DEBUGGED) ---
    with col_hint:
        st.write("💡 **Butuh Bantuan?**")
        if st.button("Minta Clue Teknis"):
            # Cari pesan terakhir assistant
            last_ai_msg = None
            for m in reversed(st.session_state.messages):
                if m["role"] == "assistant":
                    last_ai_msg = m["content"]
                    break
            
            if last_ai_msg:
                try:
                    with st.spinner("Membuat clue algoritma/konsep..."):
                        prompt_hint = f"Berikan 3 kata kunci teknis atau poin singkat (bullet points) sebagai petunjuk (clue) untuk menjawab pertanyaan ini: '{last_ai_msg}'. JANGAN berikan jawaban lengkap."
                        
                        comp = client.chat.completions.create(
                            model=MODEL_ID,
                            messages=[{"role": "user", "content": prompt_hint}],
                            temperature=0.5
                        )
                        st.session_state.hint_content = comp.choices[0].message.content
                        st.rerun()
                except Exception as e:
                    st.error(f"Gagal mengambil hint: {e}")
            else:
                st.warning("Belum ada pertanyaan dari AI.")

    with col_text:
        st.write("⌨️ **Ketik Jawaban Kode/Teks:**")
        text_input = st.chat_input("Tulis jawaban atau ketikkan algoritma/solusi...")
        if text_input: 
            current_input = text_input
            input_type = "text"

    st.write("")
    col_dummy, col_finish = st.columns([4, 1.5])
    with col_finish:
        # Safety Lock
        if len(st.session_state.messages) < 6:
            st.button("📝 Nilai Teknis (Locked)", disabled=True, help="Selesaikan minimal 2 pertanyaan teknis terlebih dahulu.")
        else:
            if st.button("📝 Akhiri & Generate Tech Report", type="primary"):
                history_text = "\n".join([f"{m['role']}: {m['content']}" for m in st.session_state.messages[-20:] if m['role'] != 'system'])
                
                # Prompt penilaian diubah menjadi kacamata orang teknikal
                prompt_nilai = f"""
                Evaluasi Technical Interview ini sebagai Senior Engineering Manager.
                {history_text}
                
                Berikan Rapor (Gunakan format Markdown):
                # HASIL EVALUASI TECHNICAL INTERVIEW
                Posisi: {job_desc}
                Fokus Pengujian: {focus_mode}
                
                TECHNICAL SCORE: [0-100]
                
                KELEBIHAN TEKNIS (Kekuatan Konsep/Coding):
                - ...
                
                KEKURANGAN TEKNIS (Area untuk Improvement):
                - ...
                
                KEPUTUSAN HIRING: [HIRED / REJECTED / FURTHER REVIEW]
                """
                
                try:
                    with st.spinner("Mengevaluasi kapabilitas teknis..."):
                        comp = client.chat.completions.create(
                            model=MODEL_ID,
                            messages=[{"role": "user", "content": prompt_nilai}],
                            temperature=0.5
                        )
                        hasil = comp.choices[0].message.content
                        st.session_state.messages.append({"role": "assistant", "content": hasil})
                        
                        pdf_bytes = create_pdf(hasil)
                        st.session_state.pdf_download = pdf_bytes
                        st.rerun()
                except Exception as e:
                    st.error(f"Gagal Menilai: {e}")

    if "pdf_download" in st.session_state:
        st.success("✅ Evaluasi Teknis Selesai!")
        st.download_button("📄 Download Rapor Penilaian IT (PDF)", st.session_state.pdf_download, "Tech_Interview_Report.pdf", "application/pdf")

    if current_input:
        st.session_state.hint_content = None # Reset hint saat user jawab
        
        if current_input != st.session_state.last_processed:
            st.session_state.last_processed = current_input
            
            user_text = ""
            if input_type == "audio":
                with st.spinner("Mendengarkan jawaban..."):
                    transcribed = speech_to_text(current_input, client)
                    if transcribed: user_text = transcribed
                    else: st.warning("Suara tidak masuk."); st.stop()
            else:
                user_text = current_input

            st.session_state.messages.append({"role": "user", "content": user_text})
            
            try:
                with st.spinner("Engineering Manager sedang mengevaluasi..."):
                    chat_completion = client.chat.completions.create(
                        model=MODEL_ID,
                        messages=get_clean_history(),
                        temperature=0.8,
                        max_tokens=300
                    )
                    ai_reply = chat_completion.choices[0].message.content
                    audio_file = asyncio.run(text_to_speech(ai_reply))
                    
                    st.session_state.messages.append({
                        "role": "assistant", "content": ai_reply, 
                        "audio_path": audio_file, "autoplay": True
                    })
                    st.rerun()
            except Exception as e:
                st.error(f"Error: {e}")
