import streamlit as st
import os
from groq import Groq
from PyPDF2 import PdfReader
import edge_tts
import asyncio
from streamlit_mic_recorder import mic_recorder 
import io
import time
from fpdf import FPDF

# --- 1. SETUP HALAMAN & CSS ---
st.set_page_config(page_title="AI Pro Interviewer", page_icon="👔", layout="wide")

st.markdown("""
    <style>
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
    .stButton>button {
        width: 100%;
        border-radius: 8px;
        font-weight: 600;
    }
    /* Kotak Hint biar lebih terlihat */
    .stInfo {
        border-left: 5px solid #FFD700 !important;
        background-color: #262730 !important;
    }
    </style>
""", unsafe_allow_html=True)

# ==========================================
# 🔑 SETTINGS
# ==========================================
GROQ_API_KEY = "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"  # <--- PASTE API KEY GROQ KAMU DI SINI
MODEL_ID = "llama-3.1-8b-instant" 
WHISPER_ID = "whisper-large-v3"
# ==========================================

# --- 2. FUNGSI PENDUKUNG ---

def get_clean_history():
    clean_msgs = []
    for m in st.session_state.messages:
        clean_msgs.append({"role": m["role"], "content": m["content"]})
    return clean_msgs

def speech_to_text(audio_bytes, client):
    try:
        audio_file = ("audio.webm", audio_bytes)
        transcription = client.audio.transcriptions.create(
            file=audio_file, model=WHISPER_ID, language="id", temperature=0.0
        )
        return transcription.text
    except:
        return None

async def text_to_speech(text):
    output_file = "ai_response.mp3"
    try:
        communicate = edge_tts.Communicate(text, "id-ID-GadisNeural")
        await communicate.save(output_file)
        return output_file
    except:
        return None

def get_pdf_text(uploaded_file):
    text = ""
    try:
        reader = PdfReader(uploaded_file)
        for page in reader.pages:
            text += page.extract_text()
    except:
        pass
    return text

def create_pdf(report_text):
    class PDF(FPDF):
        def header(self):
            self.set_font('Arial', 'B', 15)
            self.cell(0, 10, 'LAPORAN HASIL INTERVIEW', 0, 1, 'C')
            self.set_font('Arial', 'I', 10)
            self.cell(0, 10, 'Generated by AI Interviewer System', 0, 1, 'C')
            self.line(10, 30, 200, 30)
            self.ln(10)

    pdf = PDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    # Fix karakter encoding biar PDF gak error
    safe_text = report_text.encode('latin-1', 'replace').decode('latin-1')
    pdf.multi_cell(0, 10, safe_text)
    return pdf.output(dest='S').encode('latin-1')

# --- 3. SIDEBAR ---
with st.sidebar:
    st.title("⚙️ Dashboard")
    
    if GROQ_API_KEY == "gsk_..." or not GROQ_API_KEY:
        st.error("⚠️ API Key Kosong")
        st.stop()
    else:
        st.success("🟢 System Online")

    with st.expander("📄 Data Kandidat", expanded=True):
        uploaded_cv = st.file_uploader("Upload CV (PDF)", type=["pdf"])
        job_desc = st.text_area("Posisi Lamaran", placeholder="Kosongkan untuk Interview HR Umum")

    st.divider()
    st.markdown("### 🎯 Focus Mode")
    focus_mode = st.selectbox(
        "Pilih Fokus Latihan:",
        ["General (Umum)", "Leadership (Kepemimpinan)", "Problem Solving", "Technical Skill", "Pressure Test (Mental)"]
    )
    
    st.divider()
    if st.button("🔄 Reset Session"):
        st.session_state.clear()
        st.rerun()

# --- 4. LOGIC UTAMA ---
st.markdown("## 👔 Professional AI Interviewer")

client = Groq(api_key=GROQ_API_KEY)

if "messages" not in st.session_state: st.session_state.messages = []
if "last_processed" not in st.session_state: st.session_state.last_processed = None
if "interview_active" not in st.session_state: st.session_state.interview_active = False
if "hint_content" not in st.session_state: st.session_state.hint_content = None

# ==========================================
# 🚀 FLOW 1: HALAMAN MULAI
# ==========================================
if not st.session_state.interview_active:
    st.info(f"💡 Mode Aktif: **{focus_mode}**. Upload CV untuk hasil lebih akurat.")
    
    col_start, col_dummy = st.columns([1, 2])
    with col_start:
        if st.button("🚀 MULAI WAWANCARA", type="primary"):
            st.session_state.interview_active = True
            
            cv_text = get_pdf_text(uploaded_cv) if uploaded_cv else ""
            
            # Logic Konteks
            if job_desc:
                role_context = f"Posisi yang dilamar: {job_desc}"
                opening_instruction = "Langsung sapa kandidat dan tanyakan kesiapannya."
            else:
                role_context = "Konteks: Initial HR Screening (Wawancara Perkenalan Awal)."
                opening_instruction = "Sapa kandidat, lalu WAJIB mulai dengan meminta kandidat memperkenalkan diri (Tell me about yourself)."

            # Logic Focus Mode
            focus_instruction = ""
            if focus_mode == "General (Umum)":
                focus_instruction = "Fokus pada kepribadian (behavioral) dan motivasi."
            elif focus_mode == "Leadership (Kepemimpinan)":
                focus_instruction = "Fokus pada pengalaman memimpin dan manajemen konflik."
            elif focus_mode == "Problem Solving":
                focus_instruction = "Berikan studi kasus singkat."
            elif focus_mode == "Technical Skill":
                focus_instruction = "Tanyakan hard skill mendalam."
            elif focus_mode == "Pressure Test (Mental)":
                focus_instruction = "Berikan pertanyaan kritis untuk menguji mental."

            # System Prompt
            system_instruction = f"""
            Anda adalah Sarah, Senior HR Manager (Bahasa Indonesia).
            {role_context}
            Data CV: {cv_text[:2000]}.
            Mode: {focus_mode}.
            
            PANDUAN:
            1. {opening_instruction}
            2. JANGAN sebut 'General Staff'.
            3. {focus_instruction}
            4. Bicara humanis, sopan, panggil "Anda".
            5. Respon pendek (maks 3 kalimat).
            6. Tanya SATU per SATU.
            """
            
            st.session_state.messages.append({"role": "system", "content": system_instruction})

            # Trigger Start
            try:
                with st.spinner("HR sedang bersiap..."):
                    trigger_msg = "Sapa saya untuk memulai."
                    completion = client.chat.completions.create(
                        model=MODEL_ID,
                        messages=get_clean_history() + [{"role": "user", "content": trigger_msg}],
                        temperature=0.7, max_tokens=250
                    )
                    ai_msg = completion.choices[0].message.content
                    audio_file = asyncio.run(text_to_speech(ai_msg))
                    
                    st.session_state.messages.append({
                        "role": "assistant", "content": ai_msg, 
                        "audio_path": audio_file, "autoplay": True 
                    })
                    st.rerun()
            except Exception as e:
                st.error(f"Gagal Start: {e}")

# ==========================================
# 💬 FLOW 2: SESI CHAT
# ==========================================
else:
    chat_container = st.container()
    with chat_container:
        for i, msg in enumerate(st.session_state.messages):
            if msg['role'] != 'system':
                with st.chat_message(msg["role"], avatar="👩‍💼" if msg["role"] == "assistant" else "👤"):
                    st.markdown(msg["content"])
                    if "audio_path" in msg:
                        is_last = (i == len(st.session_state.messages) - 1)
                        should_play = msg.get("autoplay", False) and is_last
                        st.audio(msg["audio_path"], format="audio/mp3", autoplay=should_play)
    
    # --- TAMPILAN HINT (JIKA ADA) ---
    if st.session_state.hint_content:
        st.info(f"💡 **Ide Jawaban:**\n\n{st.session_state.hint_content}")

    st.write("---")
    
    # Input Area
    col_mic, col_hint, col_text = st.columns([1, 1, 3])
    
    current_input = None
    input_type = None

    with col_mic:
        st.write("🎤 **Bicara:**")
        audio_input = mic_recorder(start_prompt="🔴 Rekam", stop_prompt="⏹️ Kirim", key='recorder')
        if audio_input: 
            current_input = audio_input['bytes']
            input_type = "audio"

    # --- FITUR HINT FIX (DEBUGGED) ---
    with col_hint:
        st.write("💡 **Bantuan:**")
        if st.button("Bingung Jawab?"):
            # Cari pesan terakhir assistant
            last_ai_msg = None
            for m in reversed(st.session_state.messages):
                if m["role"] == "assistant":
                    last_ai_msg = m["content"]
                    break
            
            if last_ai_msg:
                try:
                    with st.spinner("Sedang memikirkan ide..."):
                        prompt_hint = f"Berikan 3 poin singkat (bullet points) ide untuk menjawab pertanyaan ini: '{last_ai_msg}'. JANGAN berikan jawaban lengkap, hanya kata kunci."
                        
                        comp = client.chat.completions.create(
                            model=MODEL_ID,
                            messages=[{"role": "user", "content": prompt_hint}],
                            temperature=0.5
                        )
                        st.session_state.hint_content = comp.choices[0].message.content
                        st.rerun()
                except Exception as e:
                    st.error(f"Gagal mengambil hint: {e}")
            else:
                st.warning("Belum ada pertanyaan dari AI.")

    with col_text:
        st.write("⌨️ **Ketik:**")
        text_input = st.chat_input("Tulis jawaban...")
        if text_input: 
            current_input = text_input
            input_type = "text"

    st.write("")
    col_dummy, col_finish = st.columns([4, 1.5])
    with col_finish:
        # Safety Lock
        if len(st.session_state.messages) < 6:
            st.button("📝 Nilai (Locked)", disabled=True, help="Jawab minimal 2 pertanyaan dulu.")
        else:
            if st.button("📝 Nilai & Report", type="primary"):
                history_text = "\n".join([f"{m['role']}: {m['content']}" for m in st.session_state.messages[-20:] if m['role'] != 'system'])
                
                prompt_nilai = f"""
                Evaluasi wawancara ini sebagai Senior HR.
                {history_text}
                
                Berikan Rapor (Markdown):
                # HASIL EVALUASI INTERVIEW
                Posisi: {job_desc if job_desc else 'Open Application'}
                Mode: {focus_mode}
                
                SKOR: [0-100]
                
                KELEBIHAN:
                - ...
                
                KEKURANGAN:
                - ...
                
                KEPUTUSAN: LOLOS / TIDAK
                """
                
                try:
                    with st.spinner("Sedang menilai..."):
                        comp = client.chat.completions.create(
                            model=MODEL_ID,
                            messages=[{"role": "user", "content": prompt_nilai}],
                            temperature=0.5
                        )
                        hasil = comp.choices[0].message.content
                        st.session_state.messages.append({"role": "assistant", "content": hasil})
                        
                        pdf_bytes = create_pdf(hasil)
                        st.session_state.pdf_download = pdf_bytes
                        st.rerun()
                except Exception as e:
                    st.error(f"Gagal Menilai: {e}")

    if "pdf_download" in st.session_state:
        st.success("✅ Penilaian Selesai!")
        st.download_button("📄 Download Rapor PDF", st.session_state.pdf_download, "Rapor_Interview.pdf", "application/pdf")

    if current_input:
        st.session_state.hint_content = None # Reset hint saat user jawab
        
        if current_input != st.session_state.last_processed:
            st.session_state.last_processed = current_input
            
            user_text = ""
            if input_type == "audio":
                with st.spinner("Mendengarkan..."):
                    transcribed = speech_to_text(current_input, client)
                    if transcribed: user_text = transcribed
                    else: st.warning("Suara tidak masuk."); st.stop()
            else:
                user_text = current_input

            st.session_state.messages.append({"role": "user", "content": user_text})
            
            try:
                with st.spinner("HR sedang mengetik..."):
                    chat_completion = client.chat.completions.create(
                        model=MODEL_ID,
                        messages=get_clean_history(),
                        temperature=0.8,
                        max_tokens=300
                    )
                    ai_reply = chat_completion.choices[0].message.content
                    audio_file = asyncio.run(text_to_speech(ai_reply))
                    
                    st.session_state.messages.append({
                        "role": "assistant", "content": ai_reply, 
                        "audio_path": audio_file, "autoplay": True
                    })
                    st.rerun()
            except Exception as e:
                st.error(f"Error: {e}")